// <auto-generated />
using System;
using MediatRAndRecordTypes.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediatRAndRecordTypes.Api.Migrations
{
    [DbContext(typeof(MediatRAndRecordTypesDbContext))]
    partial class MediatRAndRecordTypesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("MediatRAndRecordTypes")
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MediatRAndRecordTypes.Api.ConsultAggregateModel.Consult", b =>
                {
                    b.Property<Guid>("ConsultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ConsultId");

                    b.ToTable("Consults", "MediatRAndRecordTypes");
                });

            modelBuilder.Entity("MediatRAndRecordTypes.Api.ConsultAggregateModel.Consult", b =>
                {
                    b.OwnsOne("MediatRAndRecordTypes.Api.ConsultAggregateModel.DateRange", "DateRange", b1 =>
                        {
                            b1.Property<Guid>("ConsultId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("EndDate")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("datetime2");

                            b1.HasKey("ConsultId");

                            b1.ToTable("Consults", "MediatRAndRecordTypes");

                            b1.WithOwner()
                                .HasForeignKey("ConsultId");
                        });

                    b.Navigation("DateRange")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
